#pragma once
#include "DescriptorHeapContextDiplomat/DescriptorHeapContextDiplomat.h"
#include "DescriptorHeapContextDiplomat/DescriptorHeapToolLender/DescriptorHeapToolLender.h"
#include "DescriptorHeapContextDiplomat/DescriptorHeapToolLender/DescriptorHeapToolLenderLicences.h"
